# Generated by Django 5.0.3 on 2024-03-26 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=15, verbose_name='Player first name')),
                ('player_surname', models.CharField(max_length=20, verbose_name='Player last name')),
                ('player_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16, message="Player's age must be greater than 16"), django.core.validators.MaxValueValidator(45, message="Player's age must be less than 45")], verbose_name="Player's age")),
                ('contract_length', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Contract length must be greater than 0 years')], verbose_name='Contract length')),
                ('photo', models.ImageField(upload_to='media/profile_pics/', verbose_name="Hocker player's photo")),
            ],
            options={
                'verbose_name': 'Profile cart',
                'verbose_name_plural': 'Profile carts',
                'ordering': ['player_surname', 'player_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='profilecart',
            constraint=models.UniqueConstraint(fields=('player_name', 'player_surname'), name='unique_hockey_player_name_player_surname'),
        ),
    ]
